#!/bin/bash
if [[ $# -ne 1 ]]; then 
	echo "Wrong number of arguments" 
	exit 1
fi

file_name="$1"
if ! [ -f "$file_name" ]; then 
	echo "$file_name not exist"
	exit 2
fi
if ! [ -d ~/.trash ]; then
	mkdir ~/.trash
fi
name=$(ls ~/.trash | wc -l)
ln "$file_name" ~/.trash/"$name"
rm "$file_name"
echo "$(pwd)/$file_name $name" >> ~/.trash.log
 

