#!/bin/bash
awk -F " : " '
	BEGIN{cur_ppid = 0; sum = 0; cnt = 1}
	{split($2, ppid_a, "=")
	split($3, art_a, "=")
	if (cur_ppid == ppid_a[2]) {
		sum += art_a[2]
	 	cnt += 1
	 	print $0 
	} else { 
		print "Average_Sleeping_Children_of_ParentID="cur_ppid" is "sum/cnt;
		cur_ppid = ppid_a[2];
		sum = art_a[2];
		cnt = 1;
		print $0
	}}' Its4_ans | tail -n +2 > Its5_ans
