#!/bin/bash
operation="+"
ans=1
(tail -f pipe) | 
while true; do
	read LINE;
	case "$LINE" in 
		"+")	
			oreration="+"
			;;
		"*")
			operation="*"
			;;
		/[0-9]+/)
			let ans=ans"$operation""$LINE"
			echo "$ans"
			;;
		"QUIT")
			echo "Answer = $ans"
			echo "Work done"
			echo "$operation"
			kill $(cat .pid)
			exit 0
			;;
		*)
			echo "Wrong line"
			kill $(cat .pid)
			exit 1
			;;
	esac
	sleep 1s
done
