#!/bin/bash

usr1()
{
	let ans=ans+2
	echo $ans
}

usr2()
{
	let ans=ans*2
	echo $ans
}

term()
{
	echo "terminated from another proccess"
	exit 0
}

echo $$ > .pid
ans=1
trap 'usr1' USR1
trap 'usr2' USR2
trap 'term' SIGTERM

while true; do
	:
done

